### ISSUE TITLE
Binary commands sent via UART (BT) to VI eventually get corrupted

### ISSUE THREAD

**Issue by peplin** [openxc/vi-firmware#313]
I need to add more details here later but I wanted to create some record that I noticed it doesn't work reliably while working on the functional test suite running over Bluetoooth (#300).

**Comment by jwschmo** [comment]
any tips on this one? I have a use case that this would be helpful for.

**Comment by jwschmo** [comment]
I should be more clear - the "ignore binary message received by the VI" part - was there a particular reason for that? it would be helpful to have that functionality so if I can start somewhere that would be appreciated.

**Comment by peplin** [comment]
If I remember correctly, when it was enable the incoming messages would eventually get corrupted and the only way to recover was to restart the unit. I disabled it so at least it would stay up - I am not sure what the root cause might be.

**Comment by GenoJAFord** [comment]
Checked that is no longer an issue.  Turned back on the ability to send binary UART messages.
