### ISSUE TITLE
cellular_c5_config document index

### ISSUE THREAD

**Issue by mgiannikouris** [openxc/vi-firmware#326]
I noticed that @peplin would like to see the cellular config doc available from http://vi-firmware.openxcplatform.com. I think I understand how the site is generated from the various docs under version control, however I'm not sure how to add this new file to the index page docs/advanced/advanced.rst.

Just want to tag this for future work, in case someone wants to explain it to me :).

**Comment by emarsman** [comment]
I made this change. One issue is I had to change .mkd to .rst so RTD could find it. I actually found this tool which worked quite nicely: 

http://www.avilpage.com/2014/11/pandoc-best-way-to-convert-markdown-to.html

Once you have the .rst file, you just have to add it to the index toc in advanced.rst. We use sphinx to do the build. This is where I started:

https://read-the-docs.readthedocs.org/en/latest/getting_started.html

Ignore the quickstart stuff, and you can just do a 

sphinx-build(.exe) -b html . _build

in /docs and open _build/index.html locally to see your changes. 

You can install sphinx for vagrant or windows.
