### ISSUE TITLE
USB related

### ISSUE THREAD

**Issue by dsouzahansenfrancis** [openxc/vi-firmware#328]
USB speed slows down BLE connection possibly due to connection retries. Removing USB temporarily fixes this issue for now.

Bootloader red led does not blink when reading and writing to flash - related to bootloader

Remove all warnings

**Comment by peplin** [comment]
Hey, thanks, these sound like interesting issues to follow up on. I think they would be best organized as separate issues since they are not really related. I'm going to close this one - can you open new issues with a little more description for each specific bug you have found? Thanks!

**Comment by dsouzahansenfrancis** [comment]
Thanks I will create new distinct issues with more details.
