### ISSUE TITLE
about vagrant build environment 

### ISSUE THREAD

**Issue by oneway3124** [openxc/vi-firmware#331]
After I have installed the vagrant on my ubuntu 14.04 in the virtualbox,  I use the command line "fab reference build" to build the vi-firmware code. I find some error as following,
![image](https://cloud.githubusercontent.com/assets/3787176/12060997/e3dc1bc8-afb5-11e5-862c-77eb22a482de.png)
Thanks in advance if you can help me about setting up the build environment.

**Comment by peplin** [comment]
Interesting - I wonder if that package was dropped from the default OS environment. Try running `sudo pip install prettyprint` to get that package, then re-run the `fab` command.

**Comment by oneway3124** [comment]
Ok,Thanks! I know that there is some errors about python.
Right now, I have received the openxc board from us.
Although you're not one member of ford but uber, you also tell me about this project.
Thanks a great!
![img_20151231_164112_hdr 1](https://cloud.githubusercontent.com/assets/3787176/12062838/7d707c3e-afde-11e5-9789-87d4c353621f.jpg)

**Comment by oneway3124** [comment]
The compile environment hasnot been done by myself,
![image](https://cloud.githubusercontent.com/assets/3787176/12486632/743d83d4-c09e-11e5-9f31-9d5cd12ae5b5.png)

**Comment by oneway3124** [comment]
When I use the troubleshooting (http://vi-firmware.openxcplatform.com/en/master/compile/troubleshooting.html),type "git submodule update --init"
![Uploading image.png…]()

**Comment by oneway3124** [comment]
![image](https://cloud.githubusercontent.com/assets/3787176/12487049/6d4d9274-c0a0-11e5-8354-04c8daff60a6.png)

**Comment by peplin** [comment]
Looks like google code is finally gone - I see nanopb moved to Github, so I'll update the `.gitmodules` to point there. If you try making that change yourself and running `git submodule sync`, I think that will switch it to the new URL.

**Comment by oneway3124** [comment]
It seems that it is not ok until now. Can you give me some guide?

**Comment by emarsman** [comment]
Hi oneway. If you update to the 'next' branch, everything should work per Chris' recent updates. I will release next to master soon after a few more checks.
