### ISSUE TITLE
README Dead Link

### ISSUE THREAD

**Issue by ZKjellberg** [openxc/vi-firmware#335]
In the README, there is a link for 

> Installation: For the full build instructions, see the [documentation](http://vi-firmware.openxcplatform.com/en/latest/installation/installation.html).

This link provides a page stating "This page does not exist yet"

**Comment by peplin** [comment]
Sorry about that, just fixed it in 04b7805 - it's just meant to link to http://vi-firmware.openxcplatform.com/.
