### ISSUE TITLE
DoIP Diagnostic-over-IP

### ISSUE THREAD

**Issue by hackrid** [openxc/vi-firmware#337]
Any plans to support this with your VI ?

**Comment by notsig11** [comment]
That would require additional hardware (ethernet phy) so it would 
basically be a new VI.  Could be a fun project though.  :)

Is there a production vehicle using ethernet yet?  I don't think Tesla 
counts...

lee

**Comment by hackrid** [comment]
Volvo XC60 for example.

**Comment by emarsman** [comment]
Sorry, no current plans to support DoIP in the near future.
