### ISSUE TITLE
Take advantage of travis caching for dependencies

### ISSUE THREAD

**Issue by emarsman** [openxc/vi-firmware#355]
This will reduce build time, reduce download errors and external issues. Still need a way to do a full build check occasionally.

https://docs.travis-ci.com/user/caching/

**Comment by emarsman** [comment]
After above is complete, can remove the "travis_wait" from https://github.com/openxc/vi-firmware/blob/master/.travis.yml#L11

**Comment by jstoke53** [comment]
In order to complete, there would need to be changes to the BootStrap build scripts. The effort is not worth it at this time.  Closing the issue.
