### ISSUE TITLE
No Can Messages Recieved

### ISSUE THREAD

**Issue by MZein1292** [openxc/vi-firmware#377]
After flashing the Open XC FORD REFERENCE VI with the 7.2 firmware, I am not getting any CAN messages in the OpenXC enabler, but seing Dashboard information only. What is the reason for that ?

I tried installing different types of firmware bins: default, translated. Same issue occurred
I also tried different versions (7.1, 7.2).

The vehicle I am preforming the test on is: Chrysler 300 2016

attached are the screenshots

![2016-12-06](https://cloud.githubusercontent.com/assets/10118314/20931224/6b20611c-bb9e-11e6-8d4f-91928e488132.png)
![15387542_10211305577416505_1331308625_o png](https://cloud.githubusercontent.com/assets/10118314/20931235/728fe77e-bb9e-11e6-8add-d84b3794e027.jpeg)
![15354069_10211305577536508_277566818_o png](https://cloud.githubusercontent.com/assets/10118314/20931238/762f4622-bb9e-11e6-98e3-dd3a056c0af5.jpeg)

**Comment by emarsman** [comment]
This is not a firmware issue. It is working as expected. Please re-post your question to the OpenXC Google Group and I will respond there. 

https://groups.google.com/forum/#!forum/openxc
