### ISSUE TITLE
Is there any ability to provide power to OBD pins via the openxc standard?

### ISSUE THREAD

**Issue by rolandh** [openxc/vi-firmware#403]
Is there any ability in the openxc firmware specification to provide power to other IO pins?

Eg provide 5-10v on a separate OBD pin?

This is something that is specified in J2534, however J2534 is a windows only standard meaning to port J2534 functionality to Android etc you must rewrite each windows driver.

**Comment by emarsman** [comment]
No, this isn't supported easily. We do use some GPIO. However, none of them are routed to the OBD-II pins. Also, would have to check what the current limit would be and it would need to be level shifted to get above 5V. 

If you want to dig deeper, here is all the MCU config:

https://github.com/openxc/vi-firmware/tree/master/src/platform/lpc17xx

And here is the schematic. You would need to add a connection to the OBD-II pins:

http://vi.openxcplatform.com/electrical/sources/index.html

I will close this issue.
