### ISSUE TITLE
Compiling the Default Configuration - Syntax error, using vagrant

### ISSUE THREAD

**Issue by tpho216** [openxc/vi-firmware#442]
http://vi-firmware.openxcplatform.com/en/master/getting-started/development-environment.html

I followed the documentation like above and after do the command 'vagrant up' and 'vagrant ssh', I tried to run 'fab reference build' but it says I have to install fabric and, after I did 'sudo apt-get install fabric', when I run 'fab reference build', it gave me an error, 

```
vagrant@precise32:/vagrant/vi-firmware-8.0.0$ fab reference build
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/fabric/main.py", line 594, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/usr/lib/python2.7/dist-packages/fabric/main.py", line 156, in load_fabfile     
    imported = importer(os.path.splitext(fabfile)[0])
  File "/vagrant/vi-firmware-8.0.0/fabfile.py", line 249
    print(f"Make tests passed: {tests_passed}/2")
                                               ^
SyntaxError: invalid syntax
```

I have not altered anything in the default fabfile.py file in the vi-firmware-8.00 release. Then, what kind of syntax was incorrect and how do I fix this issue.

**P/S: run vagrant terminal on Visual Studio Code**
![Capture](https://user-images.githubusercontent.com/59750055/75187084-71443980-579d-11ea-8513-dbd29bb79068.PNG)

**My VirtualBox configuration**
![Capture2](https://user-images.githubusercontent.com/59750055/75187178-a81a4f80-579d-11ea-854e-72fd4b38cbdd.PNG)

**Comment by pjt0620** [comment]
Hi tpho216, I see you are using an old version of the vagrant virtual machine (Ubuntu 12) the current firmware v8.0.0 does not support old virtual machines as stated in the changelog and release notes,  fortunately this is an easy fix all you have to do re create the virtual machine.
To do this you should just have to run the below commands, be sure if you have created any items outside of the vi-firmware folder in the vm that you back them up before running the commands.
> vagrant destroy
> vagrant up

**Comment by tpho216** [comment]
> 
> 
> Hi tpho216, I see you are using an old version of the vagrant virtual machine (Ubuntu 12) the current firmware v8.0.0 does not support old virtual machines as stated in the changelog and release notes, fortunately this is an easy fix all you have to do re create the virtual machine.
> To do this you should just have to run the below commands, be sure if you have created any items outside of the vi-firmware folder in the vm that you back them up before running the commands.
> 
> > vagrant destroy
> > vagrant up

Hi I tried the following commands but still have issue with the syntax.
![Capture3](https://user-images.githubusercontent.com/59750055/75190644-d4859a00-57a4-11ea-85ee-c369783a5596.PNG)

**Comment by pjt0620** [comment]
What was the output of those commands? You still seem to have not updated to the new version of the vm.

**Comment by tpho216** [comment]
Outputs
![Capture4](https://user-images.githubusercontent.com/59750055/75191101-d3a13800-57a5-11ea-8d3e-680097f8769b.PNG)
![Capture5](https://user-images.githubusercontent.com/59750055/75191112-d69c2880-57a5-11ea-8a63-fbd636da1c3b.PNG)

**Comment by pjt0620** [comment]
Hmm Is the folder VI_Reference_firmware up to date with the git repo?

**Comment by tpho216** [comment]
> 
> 
> Hmm Is the folder VI_Reference_firmware up to date with the git repo?

![Capture7](https://user-images.githubusercontent.com/59750055/75191488-88d3f000-57a6-11ea-98d0-6b2173ecd366.PNG)

It is, I cloned it from the repo

**Comment by tpho216** [comment]
> 
> 
> Outputs
> ![Capture4](https://user-images.githubusercontent.com/59750055/75191101-d3a13800-57a5-11ea-8d3e-680097f8769b.PNG)
> ![Capture5](https://user-images.githubusercontent.com/59750055/75191112-d69c2880-57a5-11ea-8a63-fbd636da1c3b.PNG)
> ![Capture6](https://user-images.githubusercontent.com/59750055/75191388-5629f780-57a6-11ea-97e9-e526fa8d0fe8.PNG)

I'll try update to Ubuntu version 14

**Comment by pjt0620** [comment]
Thats weird, unfortunatley manually updating it wont help since the new vagrant file also sets up all of the dependencies and libraries needed for compilation. What does your Vagrantfile look like?

**Comment by tpho216** [comment]
**I have 2 vagrant files, one inside the folder D:\Workspace\VI_Reference_firmware\ -> Vagrantfile, 
look like this,** 
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "hashicorp/precise32"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

**one inside the git repo, D:\Workspace\VI_Reference_firmware\vi-firmware\ -> Vagrantfile** 
```
# -*- coding: utf-8 -*-
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

def total_cpus
  require 'etc'
  Etc.nprocessors
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # For a complete reference, please see the online documentation at
  # vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.box_version = "201912.03.0"
  config.vm.provider :virtualbox do |v|
    if total_cpus > 1
      v.cpus = total_cpus - 1
	else
	  v.cpus = 1
	end
  end
  
  # Check for proxy enviroment variable and set it
  if ENV['HTTP_PROXY'] || ENV['HTTPS_PROXY']
    if Vagrant.has_plugin?("vagrant-proxyconf")
      if ENV['HTTP_PROXY']
        config.proxy.http = ENV['HTTP_PROXY']
        config.apt_proxy.http = ENV['HTTP_PROXY']
      end
      if ENV['HTTPS_PROXY']
        config.proxy.https = ENV['HTTPS_PROXY']
        config.apt_proxy.https = ENV['HTTP_PROXY']
      end
      if ENV['NO_PROXY'] 
        config.proxy.no_proxy = ENV['NO_PROXY']
      end
    else
      abort("ERROR, vagrant-proxyconf not installed run ‘vagrant plugin install vagrant-proxyconf’ to install it") 
    end
  end

  config.vm.box_download_insecure = true
  config.vm.provision "shell", privileged: false, keep_color: true do |s|
    s.inline = "ln -fs /vagrant vi-firmware;"
    s.inline += "VAGRANT=1 vi-firmware/script/bootstrap.sh"

  end
end

```

**Comment by pjt0620** [comment]
Ok now we are getting somewhere, the one at D:\Workspace\VI_Reference_firmware\ is out of date, my guess you are running your vagrant commands from there which is why you are getting the old Ubuntu palagon box, try running the vagrant commands from within the git repo D:\Workspace\VI_Reference_firmware\vi-firmware\.

**Comment by tpho216** [comment]
> 
> 
> Ok now we are getting somewhere, the one at D:\Workspace\VI_Reference_firmware\ is out of date, my guess you are running your vagrant commands from there which is why you are getting the old Ubuntu palagon box, try running the vagrant commands from within the git repo D:\Workspace\VI_Reference_firmware\vi-firmware.

Thanks, I'll try now

**Comment by tpho216** [comment]
Successfully compiled the file. Thanks for your immediate help! We're able to close this issue
![Capture8](https://user-images.githubusercontent.com/59750055/75196915-10bef780-57b1-11ea-8e72-a281ca473a8f.PNG)
